from games.snake.snake import Snake
from games.tron.tron import Tron
from games.matrix.matrix import Matrix
#from games.tommy_wild.tommyWild import TommyWild
from games.game_of_life.gameOfLife import GameOfLife
from games.home.home import Home
from games.anim.anim import Anim
from games.simon_says.simonSays import SimonSays
from games.space_invaders.spaceInvaders import SpaceInvaders
from games.bomberman.bomberman import Bomberman
from games.pyHero.pyhero import PyHero
from games.dino.dino import Dino
from games.flappy_bird.birdGame import BirdGame
